// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKJD2LuzcVmOXEiQ0fqe2vE8xecOvAo4I',
    appId: '1:431904937340:web:871be02229a5c0690e40f9',
    messagingSenderId: '431904937340',
    projectId: 'course-connect-a3916',
    authDomain: 'course-connect-a3916.firebaseapp.com',
    storageBucket: 'course-connect-a3916.firebasestorage.app',
    measurementId: 'G-8JZ2K5W8NV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5cYmd9bwsk3sdb0WMpDpf87HXdWUeXNk',
    appId: '1:431904937340:android:be8a1721ed899a0d0e40f9',
    messagingSenderId: '431904937340',
    projectId: 'course-connect-a3916',
    storageBucket: 'course-connect-a3916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe0yI1EHdq89zbO-s8XZUv0d4T-X-C-PA',
    appId: '1:431904937340:ios:f7287ba2056589df0e40f9',
    messagingSenderId: '431904937340',
    projectId: 'course-connect-a3916',
    storageBucket: 'course-connect-a3916.firebasestorage.app',
    iosClientId: '431904937340-775l5o6j8s5g55hss55is9209ut1kchc.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe0yI1EHdq89zbO-s8XZUv0d4T-X-C-PA',
    appId: '1:431904937340:ios:f7287ba2056589df0e40f9',
    messagingSenderId: '431904937340',
    projectId: 'course-connect-a3916',
    storageBucket: 'course-connect-a3916.firebasestorage.app',
    iosClientId: '431904937340-775l5o6j8s5g55hss55is9209ut1kchc.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKJD2LuzcVmOXEiQ0fqe2vE8xecOvAo4I',
    appId: '1:431904937340:web:65f1eab24384bd010e40f9',
    messagingSenderId: '431904937340',
    projectId: 'course-connect-a3916',
    authDomain: 'course-connect-a3916.firebaseapp.com',
    storageBucket: 'course-connect-a3916.firebasestorage.app',
    measurementId: 'G-5Z3V2YV3J7',
  );

}